# Generated by Django 5.2.1 on 2025-05-17 14:53

import storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='user_files/', validators=[storage.validators.validate_file_extension]),
        ),
    ]
