services:
  - type: web
    name: cloudmunk
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn cloudstorage.wsgi:application
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: EMAIL_HOST_USER
        value: raghulkarthik21@gmail.com
